# For more advanced settings and more information about the env variables,
# please read https://github.com/fccview/jotty/blob/main/howto/DOCKER.md

services:
  jotty:
    image: ghcr.io/fccview/jotty:latest
    container_name: jotty
    user: "1001:973"
    ports:
      - "1122:3000"
    volumes:
      - ./data:/app/data:rw
      - ./config:/app/config:rw
      - ./cache:/app/.next/cache:rw
    restart: unless-stopped
    #platform: linux/arm64
    environment:
      - NODE_ENV=production
      #- HTTPS=true
      #- APP_URL=https://your-jotty-domain.com
      #- INTERNAL_API_URL=http://localhost:3000
      #- SERVE_PUBLIC_IMAGES=yes
      #- SERVE_PUBLIC_FILES=yes
      #- SSO_MODE=oidc
      #- OIDC_ISSUER=<YOUR_SSO_ISSUER>
      #- OIDC_CLIENT_ID=<YOUR_SSO_CLIENT_ID>
      #- OIDC_CLIENT_SECRET=your_client_secret
      #- SSO_FALLBACK_LOCAL=yes
      #- OIDC_ADMIN_GROUPS=admins
