services:
  jsoncrack:
    image: jsoncrack
    container_name: jsoncrack
    build: https://github.com/AykutSarac/jsoncrack.com.git
    ports:
      - "8888:8080"
    environment:
      - NODE_ENV=production
